[theme]
primaryColor="#BFA2DB"                # Soft lavender
backgroundColor="#FFFFFF"             # White background
secondaryBackgroundColor="#F3F3FA"    # Very light lavender-gray for cards
textColor = "#000000"                     
font="sans serif"
